"""
SPATUNE Web — 밸런스 테스트 음성 파일 생성 스크립트
실행: python make_audio.py
출력: audio_data.js (base64 내장 → GitHub Pages 정적 호스팅 OK)
"""
import os, base64, sys

TEXTS  = ["Left Sound", "Right Sound", "Center Sound"]
KEYS   = ["leftSound",  "rightSound",  "centerSound"]
WAVDIR = os.path.join(os.path.dirname(__file__), "audio")
JSOUT  = os.path.join(os.path.dirname(__file__), "js", "audio_data.js")

os.makedirs(WAVDIR, exist_ok=True)

# ── pyttsx3로 WAV 생성 ────────────────────────────────────
def make_with_pyttsx3():
    import pyttsx3
    engine = pyttsx3.init()
    engine.setProperty("rate", 130)
    engine.setProperty("volume", 1.0)

    # 영어 목소리 선택
    voices = engine.getProperty("voices")
    en_voice = next(
        (v for v in voices if "english" in v.name.lower() or "en_" in v.id.lower()),
        voices[0] if voices else None
    )
    if en_voice:
        engine.setProperty("voice", en_voice.id)
        print(f"Voice: {en_voice.name}")

    paths = []
    for text, key in zip(TEXTS, KEYS):
        path = os.path.join(WAVDIR, f"{key}.wav")
        engine.save_to_file(text, path)
        paths.append(path)
        print(f"Queued: {path}")

    engine.runAndWait()
    return paths


# ── fallback: scipy 사인 스윕으로 L/R 식별 음 생성 ───────
def make_with_scipy():
    import numpy as np
    import wave, struct

    SR = 22050

    def write_wav(path, samples):
        samples_int = (samples * 32767).astype(np.int16)
        with wave.open(path, "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(SR)
            wf.writeframes(samples_int.tobytes())

    def beep(freqs, dur=0.25, fade=0.02):
        t   = np.linspace(0, dur, int(SR * dur), endpoint=False)
        sig = sum(np.sin(2 * np.pi * f * t) for f in freqs) / len(freqs)
        fade_n = int(SR * fade)
        sig[:fade_n]  *= np.linspace(0, 1, fade_n)
        sig[-fade_n:] *= np.linspace(1, 0, fade_n)
        return sig * 0.7

    silence = np.zeros(int(SR * 0.1))

    # Left  : 낮은 음 두 번 (400, 500 Hz)
    # Right : 높은 음 두 번 (800, 1000 Hz)
    # Center: 낮은 음 + 높은 음
    patterns = {
        "leftSound":   np.concatenate([beep([400]), silence, beep([500])]),
        "rightSound":  np.concatenate([beep([800]), silence, beep([1000])]),
        "centerSound": np.concatenate([beep([400, 800]), silence, beep([500, 1000])]),
    }

    paths = []
    for key, samples in patterns.items():
        path = os.path.join(WAVDIR, f"{key}.wav")
        write_wav(path, samples)
        paths.append(path)
        print(f"Generated (scipy): {path}")
    return paths


# ── WAV → base64 → audio_data.js ─────────────────────────
def build_js(paths):
    lines = [
        "// SPATUNE — Embedded Audio Data (auto-generated by make_audio.py)",
        "// 각 항목은 data URL (base64 WAV) — 서버 불필요",
        "const AUDIO_DATA = {",
    ]
    for key, path in zip(KEYS, paths):
        if not os.path.exists(path):
            print(f"WARNING: {path} not found, skipping")
            continue
        size = os.path.getsize(path)
        data = base64.b64encode(open(path, "rb").read()).decode()
        lines.append(f'  {key}: "data:audio/wav;base64,{data}",  // {size//1024}KB')
    lines.append("};")
    with open(JSOUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"\nDone → {JSOUT}")


# ── 실행 ────────────────────────────────────────────────
if __name__ == "__main__":
    try:
        print("pyttsx3로 음성 생성 시도...")
        paths = make_with_pyttsx3()
        # 파일이 실제로 생성됐는지 확인
        if all(os.path.exists(p) and os.path.getsize(p) > 1000 for p in paths):
            print("pyttsx3 성공!")
        else:
            raise RuntimeError("파일 크기 이상 — scipy fallback 사용")
    except Exception as e:
        print(f"pyttsx3 실패 ({e}), scipy 음 패턴으로 대체")
        paths = make_with_scipy()

    build_js(paths)
